version: '3.7'
services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
  sensu:
    hostname: sensu
    build:
      context: server/
      dockerfile: Dockerfile 
    depends_on:
      - redis
      - rabbitmq
  api:
    hostname: api
    build:
      context: api/
      dockerfile: Dockerfile.api 
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "4567:4567"
  sensu-client:
    hostname: sensu-client
    build:
      context: client/
      dockerfile: Dockerfile.client
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "3030:3030"
  rabbitmq:
    image:       rabbitmq
    hostname:    rabbitmq
    restart:     unless-stopped
    env_file:
      - rabbitmq.env
    ports:
      - "5672:5672"   # daemon API
      - "15672:15672" # management API
  uchiwa:
    image:       uchiwa/uchiwa
    hostname:    uchiwa
    restart:     always
    depends_on:
      - rabbitmq
      - sensu
    volumes:
      - ./uchiwa-config:/config    
    ports:
      - "3000:3000"
