version: '3'
services:
  redis:
    image: redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - sensu_net
  sensu:
    hostname: sensu-server
    build: .
    image: sensu
    restart: always 
    depends_on:
      - redis
    networks:
      - sensu_net
    ports:
      - "4567:4567"  
      - "3000:3000"
  sensu-client:
    hostname: sensu-client
    build:
      context: .
      dockerfile: Dockerfile.client
    image: sensu-client
    ports:
      - "3030:3030"
    networks:
      - sensu_net
networks:
  sensu_net:
    driver: bridge
