version: '3.7'
services:
  redis:
    image: redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - sensu_net
  sensu:
    hostname: sensu-server
    build: .
    image: sensu
    restart: always 
    depends_on:
      - redis
    networks:
      - sensu_net
    ports:
      - "4567:4567"  
    expose:
      - "4567"
  sensu-client:
    hostname: sensu-client
    build:
      context: .
      dockerfile: Dockerfile.client
    image: sensu-client
    networks:
      - sensu_net
  rabbitmq:
    image:       rabbitmq
    hostname:    rabbitmq
    restart:     unless-stopped
    env_file:
      - rabbitmq.env
    ports:
      - "5672:5672"   # daemon API
      - "15672:15672" # management API
    networks:
      - sensu_net
  uchiwa:
    image:       uchiwa/uchiwa
    hostname:    uchiwa
    restart:     unless-stopped
    volumes:     
      - ./config:/config
    ports:
      - "3000:3000"
    networks:
      - sensu_net
networks:
  sensu_net:
