version: '3.7'
services:
  redis:
    image: redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - sensu_net
  sensu:
    hostname: sensu
    build: .
    image: sensu
    restart: always 
    depends_on:
      - redis
      - rabbitmq
    networks:
      - sensu_net
    ports:
      - "4567:4567"  
  sensu-client:
    hostname: sensu-client
    build:
      context: .
      dockerfile: Dockerfile.client
    image: sensu-client
    networks:
      - sensu_net
    depends_on:
      - sensu
  rabbitmq:
    image:       rabbitmq
    hostname:    rabbitmq
    restart:     unless-stopped
    env_file:
      - rabbitmq.env
    ports:
      - "5672:5672"   # daemon API
      - "15672:15672" # management API
    networks:
      - sensu_net
  uchiwa:
    image:       sstarcher/uchiwa
    hostname:    uchiwa
    restart:     always
    ports:
      - "3000:3000"
    volumes:
      - ./uchiwa.json:/etc/sensu/uchiwa.json:ro
    depends_on:
      - sensu
    networks:
      - sensu_net
networks:
  sensu_net:
